import Link from "next/link";
import { ReviewCard } from "@/components/review-card";
import {
  getReviewsByCluster,
  getReviewsByIds,
  getThemes,
} from "@/lib/queries";
import { parseFilters } from "@/lib/filters";

export const dynamic = "force-dynamic";

type SP = Record<string, string | string[] | undefined>;

export default async function ThemesPage({
  searchParams,
}: {
  searchParams: Promise<SP>;
}) {
  const sp = await searchParams;
  const themes = getThemes();

  if (themes === null) {
    return (
      <div className="rounded-lg border border-dashed border-neutral-300 bg-white p-8 text-center text-sm text-neutral-500">
        Themes table not found. Run{" "}
        <code className="rounded bg-neutral-100 px-1">npm run themes:embed</code>{" "}
        to build it.
      </div>
    );
  }

  const selected =
    typeof sp.cluster === "string" ? Number(sp.cluster) : undefined;
  const propertyId =
    typeof sp.propertyId === "string" ? sp.propertyId : undefined;

  const filters = parseFilters(sp);
  const drilldown =
    selected !== undefined
      ? {
          theme: themes.find((t) => t.cluster_id === selected),
          reviews: getReviewsByCluster(selected, filters, 100),
        }
      : null;

  return (
    <div className="space-y-6">
      <section>
        <h1 className="mb-1 text-xl font-semibold">Themes</h1>
        <p className="mb-4 text-sm text-neutral-500">
          {themes.length} clusters from 585 reviews. Embeddings via{" "}
          <code className="rounded bg-neutral-100 px-1">multilingual-e5-small</code>
          , clustering with cosine k-means (k=12). Labels generated by Claude
          Haiku 4.5 (one call per cluster). Counts come from SQL.
        </p>
      </section>

      <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {themes.map((t) => {
          const isSelected = t.cluster_id === selected;
          return (
            <Link
              key={t.cluster_id}
              href={isSelected ? "/themes" : `/themes?cluster=${t.cluster_id}`}
              className={`block rounded-lg border bg-white p-4 transition ${
                isSelected
                  ? "border-neutral-900 ring-2 ring-neutral-900/10"
                  : "border-neutral-200 hover:border-neutral-400"
              }`}
            >
              <div className="flex items-baseline justify-between">
                <h3 className="text-sm font-semibold text-neutral-900">
                  {t.label ?? `Cluster ${t.cluster_id}`}
                </h3>
                <span className="text-sm tabular-nums text-neutral-500">
                  {t.size}
                </span>
              </div>
              <p className="mt-1 text-xs text-neutral-600">
                {t.description ?? (
                  <span className="italic text-neutral-400">
                    Not labeled yet — run{" "}
                    <code className="rounded bg-neutral-100 px-1">themes:label</code>
                  </span>
                )}
              </p>
              <p className="mt-2 text-[11px] uppercase tracking-wide text-neutral-400">
                {t.size} reviews · cluster #{t.cluster_id}
              </p>
            </Link>
          );
        })}
      </section>

      {drilldown && drilldown.theme && (
        <DebugPanel
          theme={drilldown.theme}
          repReviews={getReviewsByIds(
            drilldown.theme.representative_review_ids
          )}
        />
      )}

      {drilldown && (
        <section>
          <h2 className="mb-3 text-sm font-semibold">
            {drilldown.reviews.length} review
            {drilldown.reviews.length === 1 ? "" : "s"} in &quot;
            {drilldown.theme?.label ?? `Cluster ${selected}`}&quot;
            {propertyId ? ` for ${propertyId}` : ""}
          </h2>
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
            {drilldown.reviews.map((r) => (
              <ReviewCard key={r.review_id} review={r} />
            ))}
          </div>
        </section>
      )}
    </div>
  );
}

function DebugPanel({
  theme,
  repReviews,
}: {
  theme: {
    cluster_id: number;
    label: string | null;
    description: string | null;
    labeled_at: string | null;
    size: number;
  };
  repReviews: { review_id: string; language: string; rating_overall: number; review_text: string }[];
}) {
  return (
    <details className="rounded-lg border border-dashed border-neutral-300 bg-neutral-50 p-4 text-xs">
      <summary className="cursor-pointer font-medium text-neutral-700">
        🔍 What Claude saw for this cluster — show
      </summary>
      <div className="mt-3 space-y-3 font-mono text-[11px] leading-relaxed text-neutral-700">
        <div>
          <div className="font-semibold text-neutral-900">Output:</div>
          <pre className="mt-1 whitespace-pre-wrap rounded bg-white p-2">
            {JSON.stringify(
              {
                label: theme.label,
                description: theme.description,
                labeled_at: theme.labeled_at,
              },
              null,
              2
            )}
          </pre>
        </div>
        <div>
          <div className="font-semibold text-neutral-900">
            Representative reviews sent to Claude (n={repReviews.length}):
          </div>
          <ol className="mt-1 list-decimal space-y-1 pl-5">
            {repReviews.map((r) => (
              <li key={r.review_id}>
                <span className="text-neutral-500">
                  ({r.language}, {r.rating_overall}★)
                </span>{" "}
                {r.review_text}
              </li>
            ))}
          </ol>
        </div>
      </div>
    </details>
  );
}
