/**
 * Build-time step: encodes the seeded SQLite file into a TypeScript module
 * so it's bundled into every Vercel serverless function with zero filesystem
 * juggling. Run automatically by `npm run build`.
 *
 * Re-run after `npm run db:seed`/`themes:embed`/`themes:label`.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "public", "reviews.db");
const OUT = path.join(ROOT, "src", "lib", "reviews-db.generated.ts");

if (!fs.existsSync(SRC)) {
  console.error(
    `Cannot embed DB: ${SRC} not found. Run \`npm run db:seed\` first.`
  );
  process.exit(1);
}

const bytes = fs.readFileSync(SRC);
const b64 = bytes.toString("base64");

const banner = "// AUTO-GENERATED by scripts/embed-db.ts. Do not edit. Do not commit.";
fs.writeFileSync(
  OUT,
  `${banner}\nexport const REVIEWS_DB_BASE64 = ${JSON.stringify(b64)};\n`
);

console.log(
  `Embedded ${bytes.length.toLocaleString()} bytes (${b64.length.toLocaleString()} base64 chars) into ${OUT}`
);
